services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: svodpro_qdrant

    ports:
      - "0.0.0.0:6333:6333"   # ВАЖНО: 0.0.0.0 открывает доступ снаружи

    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      # ВКЛЮЧАЕМ API KEY ДЛЯ БЕЗОПАСНОСТИ
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}